### ISSUE TITLE
bug: Revolt taskbar icon doesnt show on flatpak

### ISSUE THREAD

**Issue by LithRakoon** [revoltchat/desktop#114]
### What happened?

The Revolt taskbar icon doesnt show up when using the flatpak version of revolt
The taskbar icon does show up when using the appimage

Nobara Linux
Wayland

![image](https://user-images.githubusercontent.com/41258148/188843571-c0b7d28d-a558-4999-97d9-da35b6dcbd56.png)

**Comment by LithRakoon** [comment]
under gnome its also not available
![image](https://user-images.githubusercontent.com/41258148/192275370-d12a3eb7-1c80-4c01-9dcf-ca4158632966.png)

**Comment by Eckoa** [comment]
I have not been able to reproduce this as of recently with the Flatpak on Plasma. Is there anyone with Gnome or another DE that can confirm its still a thing?

**Comment by LithRakoon** [comment]
This seems to also not be the case for me anymore on the latest KDE on fedora 38.
Ill close this issue.
