### ISSUE TITLE
Revolt desktop on macos doesn't quit

### ISSUE THREAD

**Issue by phjo33** [revoltchat/desktop#116]
Neither the quit option in the menu nor the command-Q shortcut allows revolt-desktop to be properly shut down on macos (here on macos Monterey running on a macbook air m1) and revolt has to be force quit.

Tried the two last versions or the desktop application : 1.0.5 and 1.0.6. Same thing.

**Comment by xhayper** [comment]
This is not a bug but intended feature, when you press Command + Q, it will minimize it (aka hide it), you can make it show by clicking the revolt icon in the top bar.
