### ISSUE TITLE
bug: granting permissions to audio settings does nothing

### ISSUE THREAD

**Issue by Motzumoto** [revoltchat/desktop#117]
### What happened?

I click on the "Grant permission" thing to allow revolt to access my voice and speaker settings, but it just doesnt do anything 
[Example 1](https://i.lunardev.group/GxcEqEI/direct)

Killing the app and re-opening it with admin perms doesnt fix this issue

**Comment by Rexogamer** [comment]
Duplicate of revoltchat/revite#459.
