### ISSUE TITLE
bug: .appx certificate issue

### ISSUE THREAD

**Issue by vertigo220** [revoltchat/desktop#124]
### What happened?

Downloaded Revolt-1.0.6.appx and tried to install but get this error and can't proceed:

`This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)`

I don't like using MS store as it has issues and doesn't work as often as it does, and I currently have limited bandwidth and don't want to redownload if I can help it. Is this something I can fix on my end, or is it an issue with the installer that needs to be fixed on your end?

Win10 Version 21H2 (OS Build 19044.2364)

**Comment by vertigo220** [comment]
Since there hasn't been any response yet (understandable and not a critique) I decided to go ahead and try installing from the Windows Store since I'm really curious about this as a possible Discord replacement. Unfortunately, searching for it using various terms, including "revolt chat," failed to show it in the results. Discord, Guilded, and a bunch of other apps showed up, but I scrolled all the way to the bottom and Revolt was nowhere in there. Clicking the link on the website does appear to work (it loaded the page, but I didn't try to install it), but to me it seems like MS is working against you and censoring the search results to keep people from finding this app.

The fact that searching "revolt chat" gives Discord as the top search result and Revolt isn't there at all is extremely disturbing, indicating they are pushing users toward Discord and _away_ from Revolt. Not only does it affect the discovery of Revolt, especially since if searching specifically for it doesn't show it, searching for Discord definitely won't, even though it should realistically be the second result right after Discord in that case), it also means that people can't simply launch the store, do a quick search, and install it, but rather they have to open a web browser and go to Revolt's home page and click the link there to open it in the store.

Given MS's history of anticompetitive behavior, this very much feels to me like they've been bribed by Discord, or at the very least likely have some sort of quid pro quo arrangement, to help Discord "compete" against other products, similar to how Google favors some results and censors others. For this reason alone, not to mention the multiple other times I've had issues with the MS Store, I'd argue you shouldn't use it. Why support them by helping to give them legitimacy as a "store" when they're not only not supporting Revolt but appear to be actively doing the opposite? As much as I'd like to try Revolt, and while I was willing to use more bandwidth to redownload it from a store I already don't like, I'm simply not willing to patronize it when they're pulling this anticompetitive crap. Which, unfortunately, means I won't be trying Revolt, since that's the only other option besides the .appx which doesn't work (and itself is still using the store). Bottom line, I highly recommend just releasing it as a .exe and/or .msi.

**Comment by Rexogamer** [comment]
WhileIcan't help with the issue raised in your initial comment, two things:
- The app is currently unlisted on the Store; we initially did this because we weren't sure that it was ready, but at this point we're probably okay to mark it as public
- An installer is also available as an .exe; it's at the bottom of the list, but `Revolt-Setup-1.0.6.exe` is available [here](https://github.com/revoltchat/desktop/releases/tag/v1.0.6).

**Comment by vertigo220** [comment]
Thanks. Good to know it's not MS, well, being MS. And thanks for pointing out the .exe is there, didn't see the "Show all 18 assets" link. What's the difference between "Revolt-Setup-1.0.6.exe" and "Revolt-Windows-Setup.exe?" Both are the same size, so I'm assuming they're the same, but that would be odd, and I'd rather not download both to see, so I'll just grab the one you linked, but curious about the other.

**Comment by Rexogamer** [comment]
I wasn't entirely sure either - possibly a CI hiccup? Either way, no worries ^^

**Comment by insertish** [comment]
The AppX is built for my own convenience when publishing to the Microsoft Store.
The second install file is probably just a CI issue, not entirely sure what happened there since I last published quite a while ago. The correct installation file (that will receive updates) is indeed `Revolt-Setup-1.0.6.exe`. I've updated the release README to include more information.

Closing as resolved.
