### ISSUE TITLE
Not getting registration email when using alias service and can't change email to alias

### ISSUE THREAD

**Issue by vertigo220** [revoltchat/desktop#125]
### What happened?

I use an email alias service (33mail) for everything, which unfortunately leads to problems sometimes due to either being blocked/blacklisted or not on a whitelist. I'm not sure which is the case here, but not only does Revolt not accept it, it gives no indication of this. My friend also uses it, and he tried to register last night and as of tonight still hadn't received the email that was supposed to take at most 10 minutes. I tried tonight and also didn't get it for over 10 minutes, so I tried an alias from my email account, which is a big email provider, and then I got the registration email. Also, sometimes when this happens I just use an allowed email to register then go in and change it to an alias/33mail one, but I couldn't even do that.

So this issue is two-fold: Revolt doesn't allow 33mail, and probably other alias services, to be used to register, and it doesn't even notify of this when such an email is used, leading to wasted time waiting for an email that will never come. I'm aware of the reasoning behind not allowing such email addresses, but I also realize it's pointless, since a) popular/big email providers can be used just as easily, even more so, to make fake accounts, and b) most people that are trying to make fake accounts are probably not going to use one of these services. I've only occasionally run into this issue, and most, if not all, of the time after pointing these facts out I've been able to get the admins to change their policy regarding this, so hopefully you will as well. But if not, it should at least give the person attempting to use an email that won't work an error telling them it won't work.

Also, as a side note, when trying to change the email address in settings once logged in, if you click and drag to select the current email in order to replace it, if you drag outside the small box for changing the email, it closes it.

**Comment by insertish** [comment]
Email aliasing services are **not blocked**.

I did find a registration with 33mail however I could not find the corresponding bounce email.

Upon further investigation, I found that 33mail.com has been rejected by our mail server in the past for not being secure, it does not appear to provide TLS capabilities which is required to securely transmit emails over to the target mail server.

```
> nc -C smtp1.ec2.33mail.com. 25
220 ip-172-31-46-141.ec2.internal ESMTP SubEthaSMTP null
EHLO -snip-
250-ip-172-31-46-141.ec2.internal
250-8BITMIME
250 Ok
```

Here is an example from a reputable aliasing service:
```
# nc -C smtp-inbound1.duck.com. 25
220 smtp-inbound1.duck.com ESMTP DuckDuckGo is ready
EHLO -snip-
250-smtp-inbound1.duck.com Hello -snip- [-snip-]DuckDuckGo is ready to receive your message.
250-PIPELINING
250-8BITMIME
250-SIZE 28311552
250 STARTTLS
```

PS. this is the wrong repository to create this issue.

**Comment by insertish** [comment]
Closing due to no reply.
