### ISSUE TITLE
bug: Mic and speaker permission error

### ISSUE THREAD

**Issue by vimalraj27** [revoltchat/desktop#132]
### What happened?

The "You need to grant permission to access audio settings" pop up keeps reappearing even after selecting the mic and speaker. This happens once I select the respective devices and leave that particular page / menu.

Screenshot:
![image](https://user-images.githubusercontent.com/95607390/225103268-7c8a3aa6-4058-40f3-a652-4fdc25ffc0e8.png)

**Comment by stationaryStation** [comment]
Duplicate of revoltchat/revite [#459](https://github.com/revoltchat/revite/issues/459)

The issue will most definitely fixed in the new Client/Voice Server rewrite.

**Comment by stationaryStation** [comment]
Also, this is not an issue that is part of the desktop client as it happens on browsers, mobile and desktop.

**Comment by MimikFc7** [comment]
Hello, same trouble. Linux, Fedora 39 core 6.10.12-100.fc39.x86_64, Xfce desktop, 
Nightly 1.0.1
Native: 1.0.6
API: 0.7.14
revolt.js: 6.0.17
