### ISSUE TITLE
feature request: Raid button

### ISSUE THREAD

**Issue by KonoKore** [revoltchat/desktop#138]
### What do you want to see?

A Raid button that will lock **ALL CHANNELS** and kick members that have joined in the last 30 minutes

User: @Kono 
ID: 01GVK00NBDMQ7JECHF94SV044Z

**Comment by Rexogamer** [comment]
Wrong repository; this would require frontend/backend work, but does not involve Revolt Desktop.

**Comment by Gersonzao** [comment]
> ### What do you want to see?
> 
> A Raid button that will lock **ALL CHANNELS** and kick members that have joined in the last 30 minutes
> 
> User: @kono ID: 01GVK00NBDMQ7JECHF94SV044Z

Fyi you mentioned some random person on GitHub
