### ISSUE TITLE
fix: artifact like shapes on launch

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/desktop#14]
I don't know if it's just me or this has been reported but everytime I open Revolt this white thingy(a bug) shows.

GIF: https://not-an-iplogger.com/Fs1MtahL.gif

db43c02 (master)
Nightly 1.0.0-vite
Native: 1.0.0
API: 0.5.2-alpha.1
revolt.js: 5.0.1-alpha.6-patch.2

**Comment by aeristhy** [comment]
@insertish ping btw

**Comment by Rexogamer** [comment]
Can reproduce (albeit in a slightly different shape)

**Comment by MaXfAa** [comment]
> I don't know if it's just me or this has been reported but everytime I open Revolt this white thingy(a bug) shows.
> 
> GIF: https://not-an-iplogger.com/Fs1MtahL.gif
> 
> db43c02 (master)
> Nightly 1.0.0-vite
> Native: 1.0.0
> API: 0.5.2-alpha.1
> revolt.js: 5.0.1-alpha.6-patch.2

I have **exactly** the same thing when I launch it. It's weird 🤔
