### ISSUE TITLE
feature request: Scroll bar problem

### ISSUE THREAD

**Issue by KonoKore** [revoltchat/desktop#140]
### What do you want to see?

The scroll bar is **way** too small, it'd be best to make it a few pixels wider 

@kono
01GVK00NBDMQ7JECHF94SV044Z

**Comment by Rexogamer** [comment]
Wrong repository; this would require frontend work, but does not involve Revolt Desktop; I'm also pretty sure this is a duplicate issue?

**Comment by insertish** [comment]
Scrollbar is being made more accessible in new client.
