### ISSUE TITLE
bug: Scroll issue and text not being displayed properly in home tab on phone

### ISSUE THREAD

**Issue by Shavaizz** [revoltchat/desktop#147]
### What happened?

When you go to the home page of the revolt app on a phone (mine is the Huawei Y7 Prime 2018, I don't know for other phones if this exists or not.) the welcome text doesn't show and the whole section isn't scrollable and so i can't see the whole section. You can see this in the screenshot as well.
![Screenshot_20230419-013319](https://user-images.githubusercontent.com/58118381/232901519-6baa3528-aa9f-42b5-b0e6-7270e62c807b.jpg)

**Comment by insertish** [comment]
Superseded by https://github.com/revoltchat/frontend/issues/14
