### ISSUE TITLE
bug: DEPLOYMENT_NOT_FOUND

### ISSUE THREAD

**Issue by ae-King** [revoltchat/desktop#148]
### What happened?

![image](https://user-images.githubusercontent.com/21200584/236472992-c35a97da-5f6c-4dbc-9281-18dbd55ec451.png)

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: iad1::jjh6g-1683293796768-9cc1be4c06e5
```

The app was working yesterday. I have attempted a reinstall but this is as far as I get.

**Comment by Rexogamer** [comment]
Nightly has been taken down as it was broken for a while - try pressing Control-Shift-I, then open the Console tab and paste the following:

```js
window.native.set("build", "stable");
window.native.reload();
```

If this doesn't work, please let me know. Hope this helps :3

**Comment by Rexogamer** [comment]
Great to hear! I'll close this as solved. This probably isn't going to happen again, but we *could* add a one-time migrator? 🤔 

Anyway, gals to hear that helped ^^
