### ISSUE TITLE
feature request: Add discriminator system | 4 or 5 digits

### ISSUE THREAD

**Issue by SametChan** [revoltchat/desktop#149]
Hiya,

I am new to join Revolt chat, that would something make better than Discord again. I believe Discord is changing and messing up and also they are not going to stop when they removing the discriminator system and changing to @Username which is make more worse that can caused to spamming or nuking, stealing username possible.

I love to see if revolut chat decide to add discriminator system with 4 or just 5 digits would be great!

https://support.discord.com/hc/en-us/community/posts/14337329256983--Do-NOT-add-The-new-discord-usernames-system

This have been many people were protest against changes for discriminator to username, if discord won't stop and discord would become abandoned in later possible.

**Comment by Zomatree** [comment]
Hi thanks for the issue, however this is the wrong repository to make this issue on.

we do already have a discriminator system in the works, if you want to add any options feel free to leave a comment on the rfc https://github.com/revoltchat/rfcs/pull/3
