### ISSUE TITLE
feature request: see friends request

### ISSUE THREAD

**Issue by Zerbaib** [revoltchat/desktop#165]
### What do you want to see?

on the friends screen we don't see the request send/recieve
Can you add this

**Comment by Rexogamer** [comment]
Wrong repo - also, I'm not quite sure what you're asking for?

**Comment by Zerbaib** [comment]
on discord
![image](https://github.com/revoltchat/desktop/assets/81523999/364089ed-40e2-437d-9e52-3a0331467315)

on revolt
![image](https://github.com/revoltchat/desktop/assets/81523999/a748d1fa-8101-44b9-8955-d9859f291a1f)

i dont see where i can show my friends request

**Comment by Zerbaib** [comment]
sry i'm french TwT

**Comment by Rexogamer** [comment]
Pending requests are shown in the list below alongside your existing friends/blocked users

**Comment by Zerbaib** [comment]
i'm sorry but i don't see it

**Comment by Rexogamer** [comment]
There aren't sections at the top like Discord - instead, it's a series of collapsible lists underneath:
![image](https://github.com/revoltchat/desktop/assets/42586271/b4feca31-e583-4bb0-84bb-f1888e4dc62d)
