### ISSUE TITLE
bug: Revolt doesn't remember that I've clicked the age confirmation for NSFW channels

### ISSUE THREAD

**Issue by rado84-github** [revoltchat/desktop#166]
### What happened?

The version is 1.0.6, the OS is Arch Linux.

Revolt doesn't remember that I've clicked the age confirmation for NSFW channels (Discord does) and I have to click "enter channel" every time I click on such a channel which gets annoying.

OS: ArchLinux 
Kernel: 6.1.46-1-lts 
Uptime: 1 day, 22 hours, 46 mins 
Packages: 1337 (pacman) 
Shell: bash 5.1.16 
Resolution: 1920x1080 
DE: Cinnamon 5.2.7 
WM: Mutter (Muffin) 
WM Theme: BGT-v2.2-GTK3_Cinn-5.2.7 (Cinnamox-Rhino) 
Theme: BGT-v2.2-GTK3_Cinn-5.2.7 [GTK2/3] 
Icons: Humanity-Dark [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-4770 (8) @ 3.400GHz 
GPU: NVIDIA GeForce GTX 1660 Ti 
Memory: 7.22GiB / 31.27GiB (23%) 
GPU Driver: NVIDIA 525.89.02 
CPU Usage: 15% 
Disk (/): 27G / 112G (24%) 
Font: Open Sans Semi-Bold 11 [GTK2/3]

**Comment by Rexogamer** [comment]
Wrong repo - also, this is semi-intentional as we wanted to prevent people from accidentally opening an NSFW channel. However, we might add a toggle to remember this in the new client we're currently working on. Thanks!
