### ISSUE TITLE
bug: Is Revolt down?

### ISSUE THREAD

**Issue by MagmaBro123** [revoltchat/desktop#170]
### What happened?

Title. Both the web app and desktop app don't load. (Either that or I was banned without any warning and no You're Banned screen is implemented.)

![image](https://github.com/revoltchat/desktop/assets/51277766/f8aedb58-1973-4290-8665-109a74bbde31)

**Comment by Rexogamer** [comment]
Works for me - do you see anything in the console? (CTRL-Shift-I, then click on the Console tab)

**Comment by MagmaBro123** [comment]
No Console tab appears.

(AMD stuff does though, and I'm not messing with GPU settings, as I've broke something before.)

**Comment by Rexogamer** [comment]
Are you pressing CTRL-Shift-I while focused on Revolt Desktop itself?

**Comment by MagmaBro123** [comment]
> Are you pressing CTRL-Shift-I while focused on Revolt Desktop itself?

Yes.

**Comment by Rexogamer** [comment]
Can you show a screen recording?

**Comment by Rexogamer** [comment]
Oh! It turns out that, for some strange reason, one of AMD's apps [might be interfering with the shortcut](https://community.amd.com/t5/drivers-software/amd-relive-interfering-with-ctrl-shift-letter-shortcuts-in-other/td-p/276452). Take a look and try again?

**Comment by MagmaBro123** [comment]
Got it.

https://pastebin.com/qBw8mbe4

**Comment by MagmaBro123** [comment]
WHAT THE...

It now loads after 3 days of not working??

![image](https://github.com/revoltchat/desktop/assets/51277766/e1c80c12-6cf3-4a0b-9cd5-78e8de192846)
