### ISSUE TITLE
bug: Role list shuffles itself automatically and you cannot move roles around

### ISSUE THREAD

**Issue by Zenphia** [revoltchat/desktop#171]
### What happened?

I'm currently trying to sort out the roles in my Revolt server, but I can't move them around in the list and they seem to shuffle automatically when I'm done creating them.

<img width="145" alt="Screenshot 2023-12-07 at 21 28 27" src="https://github.com/revoltchat/desktop/assets/93544652/839046f9-f854-42fa-ae12-a7aac472b21d">

I created the colourless roles after the coloured roles. They're shuffled in with the rest of the group, for some reason.

<img width="343" alt="Screenshot 2023-12-07 at 21 28 33" src="https://github.com/revoltchat/desktop/assets/93544652/d54738fb-0200-4501-a73e-8d1788980789">

This makes using bots a lot more difficult, as a bot may complain about not being able to modify a role when you can't actually move that role to the right position.

**Comment by Zenphia** [comment]
Sorry if this isn't the right place to post this issue.

**Comment by Rexogamer** [comment]
Closing as a duplicate; assuming you're trying to drag and drop them, this is a known missing feature - you can use the rank option under each role to reorder them (lower numbers = higher ranks)
