### ISSUE TITLE
BUG: Voice Settings / Calls do not work

### ISSUE THREAD

**Issue by Supermarcel10** [revoltchat/desktop#172]
### What happened?

When attempting to make a voice call, nothing seems to happen, nor any warnings or popups show.

When going to the Voice Settings the warning/error popup stating "You need to grant permission to access audio settings." is shown.

![image](https://github.com/revoltchat/desktop/assets/47798787/b6ff4995-58a1-4fa4-ad4a-70c5b13c97c0)

Upon clicking the button, visually the popup dissapears and microphone & speaker options are shown from the dropdowns.

![image](https://github.com/revoltchat/desktop/assets/47798787/dac94670-8be4-4208-9a74-025435b4b97a)

Upon exiting the settings or going to a different tab and returning to the Voice Settings tab, the same warning/error popup is shown.

VERSION:
[782a9b5](https://github.com/revoltchat/revite/commit/782a9b54ba727418e39b86fd6f5a9678eec800d2) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 1.0.1
Native: 1.0.6
API: 0.6.6
revolt.js: 6.0.17

SYSTEM:
Windows 10 64-bit 22H2 (Build: 19045.2913)

**Comment by amycatgirl** [comment]
Not a desktop client issue. Voice calls on revolt are known for being very buggy.

They *sometimes* work, but most of the time they don't.

The voice call server (Vortex) will be rewritten after the new client (over at revoltchat/frontend) releases

**Comment by Alexander-DeLarge** [comment]
Hate to be 'that guy' but any updates/ETA? This is the only thing pending implementation halting our migration.

**Comment by insertish** [comment]
No fixes are coming for current implementation
Closing for https://github.com/revoltchat/backend/issues/313

No ETA for rewrite but currently it's "after the client refresh / native mobile releases"

**Comment by angrytardigrades** [comment]
any idea when we can expect to have voice on mobile app as well ?
