### ISSUE TITLE
Revolt will not open after installing on the Snap store on Ubuntu 24.04.1

### ISSUE THREAD

**Issue by LukeTheStarterCoder** [revoltchat/desktop#182]
### What happened?

When I install through snap, which is this command: sudo snap install revolt-desktop, it installs, but refuses to launch. And I have tried to update my AMD GPU drivers and got nothing.

**Comment by amycatgirl** [comment]
The snap store version is maintained by me, I'll move this to the correct repo and fix it in due time

**Comment by amycatgirl** [comment]
https://github.com/amycatgirl/revoltdesktop/issues/3

**Comment by sharkaccino** [comment]
closing for the above reasons. please refer to the new issue for further discussion
