### ISSUE TITLE
bug: Can't save audio settings

### ISSUE THREAD

**Issue by BrtCgn** [revoltchat/desktop#186]
### What happened?

Each time i leave the settings page, the audio settings get resetted.
Also cannot unmute myself because of this bug.

**Comment by ThePh0enix666** [comment]
Reopen issuse! In latest release (1.0.6). does not save audio settings.

**Comment by sharkaccino** [comment]
this is an issue with revite.

we're well aware of the various problems regarding the existing voice chat system. like the banner says, the current system may not work. voice chat is currently being rewritten from the ground up. the tracking issue can be found here: https://github.com/revoltchat/backend/issues/313
