### ISSUE TITLE
Add "Minimise to tray" option

### ISSUE THREAD

**Issue by ThatTonybo** [revoltchat/desktop#19]
Inspired by Discord, an option should be added that changes the close button's functionality from closing to minimising to tray. This might also include the addition of a tray icon, or alternatively could just make close act exactly like minimise (to the open apps list)

![image](https://user-images.githubusercontent.com/28176227/132073688-cd20783e-4076-4c49-9d7a-2616eccf7a9f.png)

**Comment by insertish** [comment]
Closing for earlier issue https://github.com/revoltchat/desktop/issues/2.
