### ISSUE TITLE
Package as a Flatpak + Publish on Flathub

### ISSUE THREAD

**Issue by swiperflue** [revoltchat/desktop#25]
Create a Flatpack manifest and publish on Flathub.

https://github.com/flathub/flathub/wiki/App-Submission

**Comment by iMonZ** [comment]
Any news on that? This is really important for this project

**Comment by dusansimic** [comment]
I'd like to work on this if that's okay.

**Comment by insertish** [comment]
Awesome, I'll close this issue now.

**Comment by iMonZ** [comment]
> Flatpak package is released 😁. You can find it on https://flathub.org/apps/details/chat.revolt.RevoltDesktop. For issues with flatpak package you can react out on https://github.com/flathub/chat.revolt.RevoltDesktop.

Hey found some errors:
Socket X11 should be fallback-X11 and you must add the Wayland socket to the app.

would be great if you would fix that

**Comment by dusansimic** [comment]
@iMonZ Currently there are some problems with wayland on electron on Gnome https://github.com/electron/electron/issues/27522, so once that is fixed (https://github.com/electron/electron/pull/29618) I'll probably add wayland support. Until then, there will be no change.
