### ISSUE TITLE
Activity Status still display even turned off on Revolt 

### ISSUE THREAD

**Issue by phamleduy04** [revoltchat/desktop#31]
Even I turned off `Enable Revolt status`  on settings Discord still displaying Revolt Activity Status
![image](https://user-images.githubusercontent.com/32657584/134080442-e3164ab4-402c-4830-9840-8d0c890bf472.png)

![image](https://user-images.githubusercontent.com/32657584/134080474-d15ccd87-fe09-4910-a300-4d41e733e833.png)

I'm using Windows 10 Pro 21H1 Build 19043.1237
Revolt Version
```
1614d7a (master)
Nightly 1.0.0-vite
Native: 1.0.0
API: 0.5.3-alpha.5
revolt.js: 5.1.0-alpha.0
```

**Comment by insertish** [comment]
Discord mistakenly detects Revolt as a game called Re-Volt, I can't do anything about this.
You can complain to Discord about it though.
