### ISSUE TITLE
Revolt server official badge looks weird in desktop

### ISSUE THREAD

**Issue by aeristhy** [revoltchat/desktop#46]
Screenshot in desktop: https://the-anime-god.is-inside.me/QJ3Tvpyc.png
Screenshot in webapp: https://the-anime-god.is-inside.me/8SvefOMi.png

8664cda (master)
Nightly 0.5.3-1
Native: 1.0.0
API: 0.5.3-alpha.8
revolt.js: 5.1.0-alpha.7

**Comment by insertish** [comment]
`CTRL + R` to force your client to update.

**Comment by aeristhy** [comment]
@insertish it's been over 10minutes and reloaded the client multiple times now, it's still broken

**Comment by insertish** [comment]
I didn't notice the release string, it's not patched on nightly.

**Comment by aeristhy** [comment]
btw @insertish look what i found [Issue #399](https://github.com/revoltchat/revite/issues/399) :)
