### ISSUE TITLE
i can't download desktop app form microsoft

### ISSUE THREAD

**Issue by parhammed** [revoltchat/desktop#47]
![image](https://user-images.githubusercontent.com/75374838/140603671-1ddbca7c-ba15-4464-be21-502d8c0d6fdd.png)
i can't download desktop app form microsoft

**Comment by insertish** [comment]
I just pulled it up and can't reproduce this, I don't think there's anything I can do to help since this is on Microsoft's end.
If you have any suggestions, feel free to re-open.
