### ISSUE TITLE
Auto Login Bug

### ISSUE THREAD

**Issue by Mustafa-Mert-Akceylan** [revoltchat/desktop#55]
**When I click to open the application, the login page where I am asked for my login information opens, when I click on the revolt while it is open, this time it enters the application without asking for login information.**

https://user-images.githubusercontent.com/80332192/147670727-e682a6fd-caea-4fbb-b59b-ed77ae8dc7b0.mp4

**Comment by Mustafa-Mert-Akceylan** [comment]
*This Problem Only Occurs When Revolt Nightly Is On

**Comment by Mustafa-Mert-Akceylan** [comment]
*This Problem Only Occurs When Revolt Nightly Is On

**Comment by falsisdev** [comment]
**Same!**

**Comment by Rexogamer** [comment]
Not experiencing any issues on Revolt Desktop using the nightly build of Revite - can y'all provide some more info (is this your first instal,, is this the first boot after starting up, when exactly does this happen)?

**Comment by Mustafa-Mert-Akceylan** [comment]
> Not experiencing any issues on Revolt Desktop using the nightly build of Revite - can y'all provide some more info (is this your first instal,, is this the first boot after starting up, when exactly does this happen)?

No Problem in Revolt Desktop and This problem happens all the time when nightly on
My Windows version : Win 10 21h2

**Comment by insertish** [comment]
What I think is happening is that, when you launch it twice, it can't access the stored client preferences so it instead loads **stable**. You're likely logged in on stable so it just brings you through.

**Comment by peepopoggers** [comment]
Is the app meant to save your login?

**Comment by insertish** [comment]
Marking this specific issue as invalid based on the description and earlier diagnosis.
The app does save your login provided that your branch stays the same.

Created an issue to prevent doubly launching the app: https://github.com/revoltchat/desktop/issues/82.
