### ISSUE TITLE
Revolt (all platforms) has died

### ISSUE THREAD

**Issue by diamonddev01** [revoltchat/desktop#62]
![image](https://user-images.githubusercontent.com/76881234/151879859-0fe8496a-97bd-47a6-923b-ee7e85f24143.png)
Basically everyone on revolt is 'offline' including me and I cant change my status.

Build 334e541 (master)
![image](https://user-images.githubusercontent.com/76881234/151880815-a4b2ff2d-8e64-4697-8080-8571185ccbed.png)
Heres console incase it helps (prob wont)

**Comment by Rexogamer** [comment]
This was since resolved - we're not sure what the cause was, but it affected all of their devices on two different networks
