### ISSUE TITLE
Nothing happens when pressing the button to check for updates

### ISSUE THREAD

**Issue by MaXfAa** [revoltchat/desktop#66]
When I press this button nothing happens...
![image](https://user-images.githubusercontent.com/71935156/152657117-b528e4be-132c-491e-a8da-acb89415e1a9.png)

**Comment by Rexogamer** [comment]
This is known - we haven't implemented the code for this yet

**Comment by MaXfAa** [comment]
> This is known - we haven't implemented the code for this yet

Oh, ok I see 👍

**Comment by MaXfAa** [comment]
> This is known - we haven't implemented the code for this yet

So when is it going to be implemented?

**Comment by Rexogamer** [comment]
We will get to this at some point - no ETA
