### ISSUE TITLE
The Discord status appears even if the option is disabled

### ISSUE THREAD

**Issue by MaXfAa** [revoltchat/desktop#67]
The Discord status appears even if the option is disabled...

![image](https://user-images.githubusercontent.com/71935156/152657408-17817cd5-497f-4591-9f9c-b0264a1eaf25.png)

![image](https://user-images.githubusercontent.com/71935156/152657354-b3656ddd-e9ff-4605-8a3a-5e90524fcf6a.png)

**Comment by Zomatree** [comment]
That is discord detecting `revolt.exe` as the game `Re-Volt`, this has nothing to do with the discord status option.

**Comment by MaXfAa** [comment]
> That is discord detecting `revolt.exe` as the game `Re-Volt`, this has nothing to do with the discord status option.

Oh sorry, I didn't know. But so, what is the use of this option ?
