### ISSUE TITLE
bug: rendering artifacts in random places

### ISSUE THREAD

**Issue by maxfaa** [revoltchat/desktop#68]
There is a strange rectangle a little darker that appears on the experiments page:
![image](https://user-images.githubusercontent.com/71935156/152678812-8816f2e7-d176-46fe-8774-091a1e6fd7d6.png)

**Comment by Rexogamer** [comment]
Can't reproduce locally, but I've seen several reports of this (exclusively on Desktop) so possibly an Electron bug?

**Comment by insertish** [comment]
Appears to happen anywhere, as far as I'm concerned this is an issue with the browser.
Will try to look into it when these pages are rebuilt.

https://user-images.githubusercontent.com/38285861/167600676-445d1e60-06f1-4b15-9873-f55fba5849bb.mp4

Note: disabling hardware acceleration makes the artifacts more consistent

**Comment by I2rys** [comment]
Bug still exists in the newest version but It only shows after disabling "Hardware Acceleration".

**Comment by insertish** [comment]
Closing for now, hopefully this will not come up again with the new client, otherwise a new issue will be open.
