### ISSUE TITLE
use Aononymous Network

### ISSUE THREAD

**Issue by Pantyhose-X** [revoltchat/desktop#73]
hello revolt 
Revolt There are disadvantages of being blocked by our country
Tor matrix is completely blocked in our country, l recommend Revolt to join decentralised network, https://lokinet.org

**Comment by Rexogamer** [comment]
Wrong repo - also, that site suggests the network in question works with any application so what exactly do you want us to do?

**Comment by Pantyhose-X** [comment]
@Rexogamer Hello
I want revolt to use decentralized servers to avoid the government blocking revolt servers that each user can allow, decentralizing server nodes, just like P2P
