### ISSUE TITLE
Is it possible to switch server to discord.com ? Is Revolt.chat Discord compatible?

### ISSUE THREAD

**Issue by heidiwenger** [revoltchat/desktop#74]
People recommend Revolt and likes of Fosscord, but does Revolt technically have anything to do with Discord? Just confused as on website the compatibility is not stated. Not that i found it anyway.

**Comment by lexisother** [comment]
No. It's completely separate. Revolt has nothing to do with Discord whatsoever.

**Comment by Rexogamer** [comment]
Revolt, whilst similar to Discord, is not 1:1 compatible and Revolt Desktop cannot be used as a Discord client.
