### ISSUE TITLE
Client Zooming

### ISSUE THREAD

**Issue by WapourVave** [revoltchat/desktop#8]
'CTRL -' Zooms out, however 'CTRL +' does not zoom in, instead 'Shift CTRL +' zooms instead.
Also some kind of mousewheel zooming support would feel quite natural

**Comment by ThatTonybo** [comment]
I feel mouse wheel scrolling would be very easy to accidentally trigger, and would confuse people. I often hit my scroll wheel, and my finger personally rests near CTRL, so it could be triggerable.

Also, most platforms require shift to be held to use CTRL +. Because without shift, you're hitting =, not +. Most software, even down to old/early computer BIOS' require SHIFT to be held for CTRL +.

Still, could be fixed. That's just my mind on things :)

**Comment by WapourVave** [comment]
> "I feel mouse wheel scrolling would be very easy to accidentally trigger, and would confuse people. I often hit my scroll wheel, and my finger personally rests near CTRL, so it could be triggerable."

Potentially I can see how this could be an issue for some, I've never had this issue personally inside of web browsers, but maybe having an option to enable or disable this kind of functionality could be a good middle ground for users like yourself.

> "Also, most platforms require shift to be held to use CTRL +. Because without shift, you're hitting =, not +. Most software, even down to old/early computer BIOS' require SHIFT to be held for CTRL +."

I see why what you are saying makes sense, but I feel like from a user's perspective, web browsers have normalized the usage of "Ctrl +" to zoom in. Because of this, I feel it makes sense to have a web app function effectively the same way, or atleast have an option to revert it to standard web friendly control. 

This is why I am quite pro mouse wheel when it comes to zoom control too, I feel a web app like Revolt should maintain some consistency with common keybinds a browser user may also experience.

Unrelated but I wasn't aware of the history of using "Shift Ctrl +" and thought that was quite nifty information 😛

**Comment by ThatTonybo** [comment]
> Potentially I can see how this could be an issue for some, I've never had this issue personally inside of web browsers, but maybe having an option to enable or disable this kind of functionality could be a good middle ground for users like yourself.

Absolutely a good middle ground. I can see it's potential use as well, a toggle option would be a great workaround if the functionality was added.

Regarding the second comment, I wasn't actually aware that browsers have been standardizing CTRL + without the need of SHIFT. I've always been used to using CTRL and scroll on pages (which is where my all too common scrolling in/out by accident happens), and SHIFT with CTRL + for zooming in on other applications.

Nice to know, and I do see that both could be a good QOL update.
