### ISSUE TITLE
Registration Invalid Token every time......

### ISSUE THREAD

**Issue by Freejack01** [revoltchat/desktop#81]
Everytime I register and get the email, when I click the link I get the Invalid Token message and I am unable to login.

**Comment by Freejack01** [comment]
Well figured this one out. The registration process was not taking into consideration of an alias email address being used to register and the email that it associated with it was the actual mailbox email so it failed.

**Comment by insertish** [comment]
Aliases should work just fine, it may be the case that you have registered with that email previously?

In no particular order:
- Aliases are stripped from emails when checking if they already exist in the database, but not for communication.
- This is the wrong repository, this issue should go into https://github.com/insertish/rauth/.
