### ISSUE TITLE
feature request: exit button option to minimize the application

### ISSUE THREAD

**Issue by kaname-png** [revoltchat/desktop#84]
### What do you want to see?

Currently the only way to minimize to the icon tray is to press the icon tray icon and press the "hide Revolt" button, which is impractical because it is annoying to have to open the icon tray just for that.

It would be nice if it could be configured that when pressing the exit button "x", it would be automatically minimized to the icon tray.

**Comment by stationaryStation** [comment]
I think you can already do that, go to settings -> desktop settings and enable Minimise to Tray. After a restart It should work.

Alternatively, you can do the manual and tedious fix I've found from #59
