### ISSUE TITLE
bug: Tray icon invisible

### ISSUE THREAD

**Issue by LithRakoon** [revoltchat/desktop#85]
### What happened?

The Tray icon isnt visible when revolt is open, its just a blank space

this is tested on linux:
Fedora 36
KDE Plasma
Wayland

![image](https://user-images.githubusercontent.com/41258148/168059651-ec1f3f27-af1f-4d1b-8999-3b3bf745d594.png)

**Comment by insertish** [comment]
Fixed in 16e5d094f247b1a0c532325eec8ccdd28e89b946

**Comment by LithRakoon** [comment]
just tested and its still invisible in 1.0.5
![image](https://user-images.githubusercontent.com/41258148/170053932-e6c51db7-d523-4df2-85fd-5b93bdbe03ef.png)
