### ISSUE TITLE
bug: tray icon broken on macOS

### ISSUE THREAD

**Issue by janderedev** [revoltchat/desktop#88]
### What happened?

The tray icon is a long boi white square on macOS 11.6.5.

![image](https://user-images.githubusercontent.com/26145882/168489713-2f775cb4-6303-435b-8ab8-a5e7610e02bc.png)

![image](https://user-images.githubusercontent.com/26145882/168489680-c2ba748f-d58e-432c-9742-96285d74de76.png)

**Comment by janderedev** [comment]
same on monterey btw

**Comment by 0xCUB3** [comment]
yeah same issue for me. Also when I quit or close the app I get a javascript error

**Comment by stationaryStation** [comment]
> yeah same issue for me. Also when I quit or close the app I get a javascript error

#59

**Comment by 0xCUB3** [comment]
@stationaryStation this still doesn't fix the HUGE white bar on the top, as you can see from the original post in this issue. Is there anything that can be done to fix that?

**Comment by stationaryStation** [comment]
> @stationaryStation this still doesn't fix the HUGE white bar on the top, as you can see from the original post in this issue. Is there anything that can be done to fix that?

I will try to find a fix to this issue. But I don't know a way to successfully test the fixes out since I don't have a mac around (I had one but the display gave up and died in front of my eyes)

**Comment by 0xCUB3** [comment]
@stationaryStation I'd be willing to test, although I know that is a hassle for a dev to send builds to someone else.

**Comment by janderedev** [comment]
I think I found the cause of the problem, I'll keep you guys updated

**Comment by janderedev** [comment]
Yup, fixed the problem, I'll PR the changes in later
