### ISSUE TITLE
bug: Minimize to Tray crashes on windows 10

### ISSUE THREAD

**Issue by LingKuja** [revoltchat/desktop#89]
### What happened?
Trying to minimize to tray on windows 10 (version 21h2 build 19044.1645) it returns a javascript error and crashes.
Please see the image for further details on the crash.

![Revolt_2022-05-18_22-27-45](https://user-images.githubusercontent.com/35222780/169150669-43b07c71-623a-4117-b706-82f1ae5d1075.png)

also unrelated, but the application keeps asking for permissions to use audio, both on webapp and on desktop. I already granted these but the prompt keeps resetting after I switch screen.

**Comment by insertish** [comment]
Fixed in 784c03d5a395bf4dbb1bbb440b58f4f6bddba0fd.
