### ISSUE TITLE
bug: wrong application icon

### ISSUE THREAD

**Issue by LithRakoon** [revoltchat/desktop#92]
### What happened?

Instead of showing the normal colored application icon, it now shows the what i assume to be the tray icon as the program icon
![image](https://user-images.githubusercontent.com/41258148/170054347-37818341-993a-4398-b55c-70717be1365a.png)

flatpak version: 1.0.5
windowing: x11
fedora 36

**Comment by insertish** [comment]
@janderedev

**Comment by insertish** [comment]
Also worth noting that the icon did not change for me on KDE Plasma and it's still using the correct icon in taskbar.
Not sure if it's cached somehow?

**Comment by janderedev** [comment]
Huh, interesting. Might be a flatpak thing? I'll check it out later

**Comment by LithRakoon** [comment]
this happens for me on the flatpak and on the appimage the only diffrence i saw between those 2 is that on flatpak the tray icon didn't work at all

**Comment by frolleks** [comment]
> Hey! I'm trying to work on this, but do not really know where to start. If you could, can you send a image of what it looks like so I can try to find the problem?

Too late, I already fixed it months ago
