### ISSUE TITLE
bug: Unable to log into macOS app

### ISSUE THREAD

**Issue by JoshAtticus** [revoltchat/desktop#93]
### What happened?

Whenever I try to log into my revolt account on the macOS app, i get this error
![macoserror](https://user-images.githubusercontent.com/72828296/170697597-70de1f9c-6ce3-4e0d-bb97-9ddd2cb64b48.png)

**Comment by Rexogamer** [comment]
- Are you entering your email/password correctly?
- If so, does this exclusively happen when using the desktop app?

**Comment by JoshAtticus** [comment]
> * Are you entering your email/password correctly?
> 
>     * If so, does this exclusively happen when using the desktop app?

Ah yes, I accidentally typed my password wrong on setup of account, so I just reset it (I'm still getting used to my new MacBook keyboard)
